name: FPST
channels:
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - ipykernel
  - matplotlib
  - pytorch>=1.4
  - torchvision>=0.5
  - torchtext
  - opencv
  - librosa
  - nb_conda_kernels
  - dgl>=0.4.3
  - anndata=0.7.1
  - numpy=1.18.1
  - pandas=1.0.3 
  - scikit-learn=0.22.1 
  - statsmodels=0.11.0
  - stlearn
  - pip:
    - torchviz
    - scanpy==1.8.2
    - umap-learn==0.5.2
